services:
  api:
    container_name: api-gorm-crud
    build:
      context: .
      dockerfile: api/Dockerfile
    ports:
      - "3000:3000"
    environment:
      - PORT=3000
    depends_on:
      - postgres

  postgres:
    image: postgres:15
    container_name: db-postgres-crud
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: userTest
      POSTGRES_PASSWORD: gorm123456
      POSTGRES_DB: gorm-crud
    volumes:
      - postgres_crud_data:/var/lib/postgresql/data

volumes:
  postgres_crud_data:
